CREATE TABLE Transactions (
    Transaction_ID NUMBER PRIMARY KEY,
    Account_ID NUMBER,
    Transaction_Type VARCHAR2(20),
    Amount NUMBER(10,2)
);
CREATE TABLE AuditLog (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Transaction_ID NUMBER,
    Action_Date DATE,
    Action VARCHAR2(100)
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (
        Transaction_ID,
        Action_Date,
        Action
    )
    VALUES
    (
        :NEW.Transaction_ID,
        SYSDATE,
        'New Transaction Inserted'
    );
END;
/
INSERT INTO Transactions
VALUES
(
    1,
    101,
    'Deposit',
    5000
);

COMMIT;
SELECT * FROM Transactions;
SELECT * FROM AuditLog;
